version: "3.9"

services:
  db:
    container_name: db
    image: postgres
    ports:
      - "5431:5432"
    restart: always
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: b4Dg3r

  backend:
    container_name: backend
    build: backend/
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
    ports:
      - "8082:8082"
    restart: always

  frontend:
    container_name: frontend
    build: frontend/
    ports:
      - "4200:80"
